[package]
name = "fastsar"
version = "0.1.0"
authors = ["Armin Grodon <me@armingrodon.de>"]
description = "Switch between AWS roles quickly using fuzzy matching"
documentation = "https://github.com/x4121/fastsar-rs"
homepage = "https://github.com/x4121/fastsar-rs"
repository = "https://github.com/x4121/fastsar-rs"
keywords = ["aws", "sts"]
categories = ["command-line-utilities"]
license = "MIT"
readme = "README.md"
edition = "2018"

[[bin]]
name = "fastsar"
bench = false

[dependencies]
anyhow = "~1.0"
config = "~0.10"
futures = "~0.3"
log = "~0.4"
rusoto_core = "~0.46"
rusoto_credential = "~0.46"
rusoto_sts = "~0.46"
serde_derive = "~1.0"
serde_json = "~1.0"
shellexpand = "~2.1"
simplelog = "~0.9"
skim = "~0.9"
structopt = "~0.3"
subprocess = "~0.2"
termcolor = "~1.1"

[dependencies.serde]
features = ["derive"]
version = "~1.0"

[dependencies.tokio]
features = ["full"]
version = "~1.0"

[dev-dependencies]
quickcheck = "~1.0"
quickcheck_macros = "~1.0"
rusoto_mock = "~0.46"
tokio-test = "~0.4"

[dev-dependencies.rusoto_sts]
features = ["serialize_structs"]
version = "~0.46"
