name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  build_musl:
    name: Build musl binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: heroku/rust-cargo-musl-action@v1
        with:
          command: 'build'
          flags: '--release --all-features'
      - uses: actions/upload-artifact@v2
        with:
          name: fastsar
          path: ${{ steps.compile.outputs.release-dir }}/fastsar

  build_osx:
    name: Build OSX binary
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - uses: actions/upload-artifact@v2
        with:
          name: fastsar
          path: ${{ steps.compile.outputs.release-dir }}/fastsar
